### PR TITLE
#46 - Add basic pages

### PR DESCRIPTION
**Pull request by leresolu**
I added the basic apges using nuxt but they're empty now, at least the URL works

### CODE REVIEW

**Comment by vitaly-savin** [comment]
Everything is fine

**Review by vitaly-savin — DISMISSED** [review]

**Review by PanteaMartia — DISMISSED** [review]

**Review by gffilho — CHANGES_REQUESTED** [review]
Could you add, please, the boilerplate?

**Review by TianaSantatraR — APPROVED** [review]

**Review by PanteaMartia — COMMENTED** [review]
Hi, I saw changes

**Review by PanteaMartia — APPROVED** [review]

**Review by gffilho — APPROVED** [review]
Good job!!!

**Pull request merged**
